### PR TITLE
Minor adjustments to GRPluginStands

### PR DESCRIPTION
**Pull request by Atriusftw**
1. Add M3 for ambulances on ENVA

image

2. Add GA on ENZV

image

### CODE REVIEW

**Comment by Atriusftw** [comment]
I think it's fine to keep these as radiuses, as they are areas.

**Comment by Adrian2k** [comment]
Would recommend changing the GA area at ENZV to a polygon instead, covering the whole apron.

**Comment by Adrian2k** [comment]
Also for ENZV, business jets should be parked by the 3 stands by the TWR. Stand 301, 302, 303

**Comment by Atriusftw** [comment]
Noted. Will fix these things tomorrow :)

**Comment by Atriusftw** [comment]
Commited the changes now
image

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
