### PR TITLE
GM DEP/ARR MAPS + RNP

### LINKED ISSUE #423: Add transitions to GM STAR maps

### PR DESCRIPTION
**Pull request by Sanderli25**
Resolves #423 

- Updated GM-STAR for 19 and 01
- Updated SID maps for 19 and 01
- Added PROP SIDs for 01L, 19L and 19R
- Added map with names for all SIDs
- Added PIVAT in Transit route map, but without line as it is not mandatory
- Updated all GM RNPs
- New RNP blue colour defined
- Removed unnecessary text in noise abatement map for 19 and 01

### CODE REVIEW

**Comment by Adrian2k** [comment]
In the future, when you make everything into coordinates - please make remakrs in the code which section is what.
Otherwise it is a nightmare to figure out later when you want to make any changes.

**Comment by Adrian2k** [comment]
The transition parts are quite "visible".
IRL they use a smaller dots, which is not possible in ES.

Can we either
1. Make the transitions a sepearte map
or
2. Desaturate the colors in transitions, so it is less in the way

Example:
image
COLORDEF:TRANSITION:102:89:45

**Comment by Adrian2k** [comment]
image

While I am aware this is how the map is drawn IRL, it is actually incorrect.

GM437 is mandatory flyover, so aircrafts has to pass the point before turning. They are also then to intercept a R280 from GM437 towards GM439.

I think it will be more correct to use the map we already had for this - it can also be less confusing for new controllers on ENGM who have not studied the SID charts to full details.

image

**Comment by Adrian2k** [comment]
Also where is the east/west SID maps now?

**Comment by Adrian2k** [comment]
SID maps also have to be updated in the ground radar plugin maps folder

**Review by Adrian2k — CHANGES_REQUESTED** [review]
as above

**Comment by Sanderli25** [comment]
> The transition parts are quite "visible".
> 
> IRL they use a smaller dots, which is not possible in ES.
> 
> 
> 
> Can we either
> 
> 1. Make the transitions a sepearte map
> 
> or
> 
> 2. Desaturate the colors in transitions, so it is less in the way
> 
> 
> 
> Example:
> 
> image
> 
> COLORDEF:TRANSITION:102:89:45
> 
> 
> 
> 
> 
> (Current for reference:)
> 
> image
> 
> 

I like suggestion number 2. Will update.

**Comment by Sanderli25** [comment]
> image
> 
> 
> 
> While I am aware this is how the map is drawn IRL, it is actually incorrect.
> 
> 
> 
> GM437 is mandatory flyover, so aircrafts has to pass the point before turning. They are also then to intercept a R280 from GM437 towards GM439.
> 
> 
> 
> I think it will be more correct to use the map we already had for this - it can also be less confusing for new controllers on ENGM who have not studied the SID charts to full details.
> 
> 
> 
> image
> 
> 

Actually disagree on this one. The map does not need to be a 100% representation of the flight path. The hump is more coordinates for basically nothing. Can perhaps make the turn start a bit further north.

**Comment by Sanderli25** [comment]
> Also where is the east/west SID maps now?

Can add back. Shall these be dot? Never seen these in reference photos. If dot, they will match prop.

**Comment by Sanderli25** [comment]
> SID maps also have to be updated in the ground radar plugin maps folder

Forgot these existed.

It's not my call, but is it necessary with SID in the APP window? Never seen this in any reference photos. Could save some lines by deleting, and free the hassle of updating multiple places during changes.

**Comment by Adrian2k** [comment]
> > Also where is the east/west SID maps now?
> 
> Can add back. Shall these be dot? Never seen these in reference photos. If dot, they will match prop.

See picture I sent you on discord



> > SID maps also have to be updated in the ground radar plugin maps folder
> 
> Forgot these existed.
> 
> It's not my call, but is it necessary with SID in the APP window? Never seen this in any reference photos. Could save some lines by deleting, and free the hassle of updating multiple places during changes.

Unfortunately I did not seem to document the reason for adding these anywhere - but I recall it being requested by multiple people to have it added there.

Yes it is a pain to keep everything updated, this is a consequence of using manually mapped maps instead of autogenerated ones.

**Comment by Sanderli25** [comment]
All issued fixed.

**Pull request merged**
